# Phương Thức Nhập
InputMethod=Telex
# Bảng Mã
OutputCharset=Unicode
# Bật kiểm tra chính tả
SpellCheck=False
# Bật gõ tắt
Macro=False
# Xử lý ký tự bắt đầu là W
ProcessWAtBegin=True
# Tự động khôi phục phím với từ sai
AutoNonVnRestore=True
# Đặt dấu kiểu oà, _uý (thay vì òa, úy)
ModernStyle=True
# Cho phép gõ tự do
FreeMarking=True
# Phục hồi trạng thái gõ phím bằng surrounding 
SurroundingText=True
# Cho phép sửa từ đã gõ (thử nghiệm)
ModifySurroundingText=False
# Gạch chân từ đang viết
DisplayUnderline=False

