#!/usr/bin/env bash
# Omarchy hook: generate swaync color definitions from pacsea/theme.conf
set -euo pipefail
PACSEA="$HOME/.config/pacsea/theme.conf"
OUT="$HOME/.config/swaync/omarchy-swaync-colors.css"

[ -f "$PACSEA" ] || exit 0
mkdir -p "$(dirname "$OUT")"

# helper to read value (strips spaces)
val(){
  awk -F'=' -v k="$1" '$1~k{gsub(/ /,"",$2); print $2; exit}' "$PACSEA"
}

background_base=$(val "background_base")
surface_level1=$(val "surface_level1")
surface_level2=$(val "surface_level2")
text_primary=$(val "text_primary")
text_secondary=$(val "text_secondary")
accent_interactive=$(val "accent_interactive")
accent_heading=$(val "accent_heading")
semantic_error=$(val "semantic_error")
overlay_primary=$(val "overlay_primary")
overlay_secondary=$(val "overlay_secondary")

cat > "$OUT" <<EOF
/* Generated by Omarchy hook: do not edit manually */

@define-color surface ${background_base:-#1c1e26};
@define-color surface_container ${surface_level1:-#1c1e26};
@define-color surface_container_low ${surface_level2:-#fadad1};
@define-color on_surface ${text_primary:-#fadad1};
@define-color on_surface_variant ${text_secondary:-#6c6f93};

@define-color primary ${accent_interactive:-#26bbd9};
@define-color on_primary ${text_primary:-#fadad1};

@define-color error ${semantic_error:-#e95678};
@define-color on_error #ffffff;

@define-color shadow #000000;
@define-color secondary ${overlay_secondary:-#3fc4de};
@define-color secondary_container ${overlay_primary:-#26bbd9};
@define-color surface_container_high ${surface_level1:-#1c1e26};
@define-color surface_container_highest ${surface_level1:-#1c1e26};
@define-color outline ${text_secondary:-#6c6f93};
@define-color outline_variant ${text_secondary:-#6c6f93};
EOF

# make sure file is readable
chmod 644 "$OUT"
