-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        no_hardware_cursors = 2,
    },
    decoration = {
        blur = {
            enabled = false,
            ignore_opacity = true,
            noise = 0.17,
            passes = 2,
            size = 3,
            xray = false,
        },
    },
    dwindle = {
        smart_split = false,
    },
    ecosystem = {
        no_donation_nag = true,
    },
    misc = {
        vrr = 1,
    },
    scrolling = {
        column_width = 0.5,
        follow_min_visible = 0.4,
    },
})
