-- Generated by nomarkoo.keyboard-layout. Use the bar panel to edit this file.
hl.config({
  input = {
    kb_layout = "us",
    kb_variant = "",
    kb_options = "compose:caps,shift:both_capslock_cancel,grp:alt_shift_toggle",
  },
})
