#!/usr/bin/env python3.14
"""Generate bap_cc_theme.css from a theme's colors.toml.

Reads the matugen palette (background, foreground, accent, color0-15) and emits
a GTK CSS file with @define-color entries so the BAP Control Center follows the
active Omarchy theme. Used by the 60-bap-cc.sh theme-set hook.
"""
import sys, tomllib
from pathlib import Path

if len(sys.argv) < 2:
    sys.exit(1)

colors = tomllib.loads(Path(sys.argv[1]).read_bytes().decode())

def g(k, default="#000000"):
    v = colors.get(k, default)
    return v if v.startswith("#") else f"#{v}"

bg = g("background")
fg = g("foreground")
acc = g("accent", g("color4"))
black = g("color0", bg)
white = g("color7", fg)
blue = g("color4", acc)
cyan = g("color6", "#89dceb")
red = g("color1", "#f38ba8")
green = g("color2", "#a6e3a1")
yellow = g("color3", "#f9e2af")

out = f"""/* Auto-generated by 60-bap-cc.sh — follows Omarchy theme. DO NOT EDIT. */
@define-color black   {black};
@define-color white   {white};
@define-color blue    {blue};
@define-color cyan    {cyan};
@define-color red     {red};
@define-color green   {green};
@define-color yellow  {yellow};

@define-color background     {bg};
@define-color foreground     {fg};

@define-color accent_bg_color {acc};
@define-color accent_fg_color {bg};
@define-color accent_color    {acc};

@define-color window_bg_color {bg};
@define-color window_fg_color {fg};
@define-color view_bg_color   {bg};
@define-color view_fg_color   {fg};
@define-color card_bg_color   {bg};
@define-color card_fg_color   {fg};

@define-color headerbar_bg_color {bg};
@define-color headerbar_fg_color {fg};

@define-color sidebar_bg_color   {bg};
@define-color sidebar_fg_color   {fg};
@define-color popover_bg_color   {bg};
@define-color popover_fg_color   {fg};
@define-color dialog_bg_color    {bg};
@define-color dialog_fg_color    {fg};

@define-color destructive_bg_color {red};
@define-color destructive_fg_color {bg};
@define-color success_bg_color     {green};
@define-color success_fg_color     {bg};
@define-color warning_bg_color     {yellow};
@define-color warning_fg_color     {bg};

@define-color error_color         {red};
@define-color error_bg_color      {red};
@define-color error_fg_color      {bg};
@define-color success_color       {green};
@define-color warning_color       {yellow};
@define-color destructive_color   {red};
@define-color destructive_fg_color {bg};

@define-color borders alpha({fg}, 0.10);
"""
sys.stdout.write(out)
