#!/usr/bin/env bash

# Omarchy theme hook: export Omarchy colors into Pacsea theme.conf
# This script runs from Omarchy's `theme-set` so color vars are exported
# (e.g., primary_background, primary_foreground, normal_red, etc.).

out="$HOME/.config/pacsea/theme.conf"

cat >"$out" <<EOF
# Generated by Omarchy hook: do not edit manually
background_base = #${primary_background:-000000}
background_mantle = #${primary_background:-000000}
background_crust = #${normal_black:-000000}

surface_level1 = #${normal_black:-000000}
surface_level2 = #${normal_white:-ffffff}

overlay_primary = #${normal_blue:-7f849c}
overlay_secondary = #${bright_blue:-9399b2}

text_primary = #${primary_foreground:-ffffff}
text_secondary = #${bright_black:-a6adc8}
text_tertiary = #${bright_white:-bac2de}

accent_interactive = #${normal_blue:-74c7ec}
accent_heading = #${normal_magenta:-cba6f7}
accent_emphasis = #${bright_magenta:-b4befe}
semantic_success = #${normal_green:-a6e3a1}
semantic_warning = #${normal_yellow:-f9e2af}
semantic_error = #${normal_red:-f38ba8}
EOF

# If Omarchy exported require_restart(), call it to mark pacsea for restart
if command -v require_restart >/dev/null 2>&1; then
    require_restart pacsea || true
fi

# Print success message when run interactively
if [[ -t 1 ]]; then
    echo "[omarchy->pacsea] wrote $out"
fi
