-- Generated by OmaSettings (omasettings:managed) — do not edit by hand.
-- Every value here was set from the OmaSettings window; delete a line
-- to hand that setting back to your own config.

hl.config({
  input = {
    accel_profile = "flat",
  },
})

hl.config({
  general = {
    gaps_out = 6,
  },
})

