# Application bindings

$terminal = uwsm app -- alacritty
$browser = uwsm app -- google-chrome-stable --new-window --ozone-platform=wayland
$webapp = $browser --app
$files = thunar # File Manager
$edit=${EDITOR:-nano}
