# Extra autostart processes
# exec-once = uwsm-app -- my-service
 
 # Fcitx5
 exec-once = fcitx5

# Random Wallpaper
 exec-once = /home/bap/.local/bin/rand-wallpaper.sh
 
 #swaync
 exec-once = swaync &
 
 #hypr-dock
exec-once = sleep 10 && nwg-dock-hyprland -d -x -p "bottom"  -i 38 -mr 10 -ml 10 -mb 5 -lp start -ico /home/bap/.config/nwg-dock-hyprland/arch.png -s /themes/glass/style.css 

 
 #pyprland
exec-once = /usr/bin/pypr

exec-once = ~/.config/hypr/scripts/sidepad-autohide.sh
exec-once = ~/.config/hypr/scripts/sidepad-hover.sh
exec-once = snappy-switcher --daemon
exec-once = ~/.local/bin/auto-sort-downloads.sh
