# Extra autostart processes
exec-once = $systemBridge
exec-once = $browserPersonal
exec-once = twitch-notifications
exec-once = solaar --window=hide

# Wallpaper-engine
exec-once = omarchy-we launch

# Workspace layouts
exec-once = workspace-setup --sleep=5

 # Fcitx5
 exec-once = fcitx5 -d &

 # ## Slow app launch fix
exec-once = systemctl --user import-environment &
exec-once = hash dbus-update-activation-environment 2>/dev/null &
exec-once = dbus-update-activation-environment --systemd &

 # Aria2
exec-once = aria2c --conf-path=/home/$USER/.config/aria2/aria2.conf

# Random Wallpaper
# exec-once = /home/bap/.local/bin/rand-wallpaper.sh

 #swaync
#exec-once = swaync &

 #nwg-dock-hyprland
 exec-once = sleep 10 && nwg-dock-hyprland -d -x -p "bottom"  -i 40 -mr 10 -ml 10 -mb 5 -lp start

 #-ico /home/bap/.config/nwg-dock-hyprland/arch.png -s /themes/glass/style.css

#quickshell-dock
# exec-once = quickshell -p ~/.config/quickshelldock

#hyprpm
exec-once = hyprpm reload -n

 #pyprland
exec-once = /usr/bin/pypr

exec-once = ~/.config/hypr/scripts/sidepad-autohide.sh
exec-once = ~/.config/hypr/scripts/sidepad-hover.sh
exec-once = snappy-switcher --daemon
exec-once = ~/.local/bin/auto-sort-downloads.sh
