# Application bindings

$terminal = uwsm app -- kitty
$browser = uwsm app -- google-chrome-stable --new-window --ozone-platform=wayland
$webapp = $browser --app
$files = nautilus # File Manager
$edit=${EDITOR:-nano}
