# Floating windows weather-tui
windowrule = float on, match:tag floating-weather-tui
windowrule = center on, match:tag floating-weather-tui
windowrule = size 993 742, match:tag floating-weather-tui

windowrule = tag +floating-weather-tui, match:class custom.weather.tui
windowrule = tag +floating-weather-tui, match:class custom.weather.tui
